import 'package:courier_delivery/presentation/marketplace_screen/model/bid_model.dart';

class BidData {
  static List<BidModel> getBidData() {
    return [
      BidModel(
          'S001',
          'V001',
          'image1.png',
          'Steel',
          '1000kg',
          '5000',
          '4500',
          '7 days',
          '3 days',
          'New York',
          'High-quality steel material',
          '2024-06-28',
          'None',
          'New',
          'Open'),
      BidModel(
          'S002',
          'V002',
          'image2.png',
          'Wood',
          '500 pieces',
          '3000',
          '2500',
          '5 days',
          '2 days',
          'Los Angeles',
          'Premium oak wood',
          '2024-06-28',
          'None',
          'New',
          'Open'),
      BidModel(
          'S003',
          'V003',
          'image3.png',
          'Plastic',
          '2000 units',
          '2000',
          '1500',
          '10 days',
          '6 days',
          'Chicago',
          'Durable plastic material',
          '2024-06-28',
          'None',
          'New',
          'Open'),
      BidModel(
          'S004',
          'V004',
          'image4.png',
          'Aluminum',
          '1500kg',
          '7000',
          '6500',
          '8 days',
          '4 days',
          'Houston',
          'High-grade aluminum',
          '2024-06-28',
          'None',
          'New',
          'Open'),
    ];
  }
}
